# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160831_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='appkey',
            field=models.CharField(max_length=128, unique=True, verbose_name='App Key'),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='usergameorder',
            name='game_order_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='\u6e38\u620f\u5546\u8ba2\u5355id'),
        ),
    ]
