# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160908_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='appkey',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='App Key'),
        ),
    ]
