# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20161009_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iapreceipthistory',
            name='iap_digest',
        ),
        migrations.AddField(
            model_name='iapreceipthistory',
            name='receipt_digest',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u82f9\u679c\u652f\u4ed8\u9a8c\u8bc1\u4e32\u6458\u8981'),
        ),
    ]
