# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20161024_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyAppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thirdparty', models.CharField(choices=[('facebook', 'facebook'), ('google', 'google')], max_length=64)),
                ('info', models.TextField(blank=True, null=True, verbose_name='in JSON format')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.App')),
            ],
        ),
    ]
