# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-25 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_thirdpartyappinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thirdpartyappinfo',
            unique_together=set([('app', 'thirdparty')]),
        ),
    ]
