# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160826_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='download_urls',
        ),
        migrations.AddField(
            model_name='app',
            name='download_link',
            field=models.TextField(default='', verbose_name='App download url'),
        ),
    ]
