# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160827_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify_code_create_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify_code_expire_at',
        ),
    ]
