# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20161003_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='iapreceipthistory',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '\u672a\u9a8c\u8bc1'), (1, '\u5df2\u9a8c\u8bc1')], default=0, verbose_name='\u8bb0\u5f55\u5f53\u524d\u8ba2\u5355\u662f\u5426\u5df2\u7ecf'),
        ),
    ]
