# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_iapreceipthistory_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='iapreceipthistory',
            name='original_purchase_date_ms',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='iTunes IAP original_purchase_date_ms'),
        ),
        migrations.AddField(
            model_name='iapreceipthistory',
            name='original_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='iTunes IAP original_transaction_id'),
        ),
        migrations.AddField(
            model_name='iapreceipthistory',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='iTunes IAP product_id'),
        ),
        migrations.AddField(
            model_name='iapreceipthistory',
            name='purchase_date_ms',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='iTunes IAP purchase_date_ms'),
        ),
        migrations.AddField(
            model_name='iapreceipthistory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='iTunes IAP quantity'),
        ),
        migrations.AddField(
            model_name='iapreceipthistory',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='iTunes IAP transaction_id'),
        ),
    ]
