# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20161010_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAPReceiptHistory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iap_digest', models.CharField(default='', max_length=255, unique=True, verbose_name='\u82f9\u679c\u652f\u4ed8\u9a8c\u8bc1\u4e32\u7684md5\u503c')),
                ('trade_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='\u652f\u4ed8\u4e2d\u5fc3\u8ba2\u5355id')),
                ('state', models.SmallIntegerField(choices=[(0, '\u672a\u9a8c\u8bc1'), (1, '\u5df2\u9a8c\u8bc1')], default=0, verbose_name='\u8bb0\u5f55\u5f53\u524d\u8ba2\u5355\u662f\u5426\u5df2\u7ecf')),
                ('bundle_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='iOS bundle_id')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='iTunes IAP quantity')),
                ('product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='iTunes IAP product_id')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='iTunes IAP transaction_id')),
                ('purchase_date_ms', models.BigIntegerField(blank=True, null=True, verbose_name='iTunes IAP purchase_date_ms')),
                ('original_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='iTunes IAP original_transaction_id')),
                ('original_purchase_date_ms', models.BigIntegerField(blank=True, null=True, verbose_name='iTunes IAP original_purchase_date_ms')),
                ('is_sandbox', models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u6c99\u7bb1\u73af\u5883')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IAPReceiptHistory',
        ),
    ]
