# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20161010_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iapreceipthistory2',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '\u672a\u9a8c\u8bc1'), (1, '\u9a8c\u8bc1\u6210\u529f'), (2, '\u9a8c\u8bc1\u5931\u8d25')], default=0, verbose_name='\u8bb0\u5f55\u5f53\u524d\u8ba2\u5355\u662f\u5426\u5df2\u7ecf'),
        ),
        migrations.AlterField(
            model_name='usergameorder',
            name='order_status',
            field=models.CharField(choices=[('I', '\u5f85\u4ed8\u6b3e'), ('S', '\u4ea4\u6613\u6210\u529f'), ('F', '\u4ea4\u6613\u5931\u8d25'), ('R', '\u9000\u6b3e'), ('C', '\u4ea4\u6613\u5173\u95ed'), ('SS', 'iTunes Sandbox\u4ea4\u6613\u6210\u529f'), ('E', 'iTunes \uff08\u7ebf\u4e0a\u73af\u5883\uff09\u4ea4\u6613\u5f02\u5e38')], db_index=True, max_length=2, verbose_name='\u8ba2\u5355\u72b6\u6001'),
        ),
    ]
