# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-22 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20161018_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_userid', models.CharField(max_length=128, unique=True)),
                ('extra_info', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='guid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='guid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='register at'),
        ),
        migrations.AddField(
            model_name='fbuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
