# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('appid', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='App ID')),
                ('package_name', models.CharField(db_index=True, max_length=128, verbose_name='Package Name')),
                ('name', models.CharField(db_index=True, default='', max_length=128, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=512, verbose_name='Short Description')),
                ('description_long', models.TextField(default='', verbose_name='Long Description')),
                ('appkey', models.CharField(db_index=True, default='', max_length=128, verbose_name='App Key')),
                ('paykey', models.CharField(default='', max_length=128, verbose_name='Pay key')),
                ('latest_version_desc', models.CharField(max_length=128, verbose_name='\u66f4\u65b0\u63cf\u8ff0')),
                ('latest_version_number', models.IntegerField(default=1, verbose_name='version (int)')),
                ('support_version_list', models.CharField(max_length=128, verbose_name='version support list')),
                ('download_urls', models.TextField(default='', verbose_name='App download urls, JSON dict')),
                ('is_standalone', models.IntegerField(default=0, verbose_name='\u662f\u5426\u662f\u5355\u673a\u5e94\u7528')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='create at')),
                ('update_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='update at')),
                ('disabled', models.DateTimeField(db_index=True, null=True, verbose_name='disabled')),
            ],
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u5b57')),
                ('identifier', models.CharField(max_length=20, verbose_name='\u6807\u793a\u7b26')),
                ('seq', models.IntegerField(unique=True, verbose_name='\u4f18\u5148\u7ea7(\u5c0f\u6570\u5b57\u4f18\u5148)')),
                ('status', models.IntegerField(verbose_name='\u652f\u4ed8\u65b9\u5f0f\u603b\u5f00\u5173 0-\u5173 1-\u5f00')),
            ],
            options={
                'verbose_name': '\u652f\u4ed8\u65b9\u5f0f',
                'verbose_name_plural': '\u652f\u4ed8\u65b9\u5f0f',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='pay_type',
            field=models.ManyToManyField(to='api.PayType', verbose_name='\u652f\u6301\u7684\u652f\u4ed8\u65b9\u5f0f'),
        ),
    ]
