# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_app_version_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='latest_version_number',
            new_name='latest_version_code',
        ),
    ]
