# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='User Phone Number'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('username', 'phone')]),
        ),
    ]
