# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_iapreceipthistory_is_sandbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iapreceipthistory',
            name='is_sandbox',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u6c99\u7bb1\u73af\u5883'),
        ),
    ]
