# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-10 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20161010_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iapreceipthistory',
            name='receipt_digest',
        ),
        migrations.AddField(
            model_name='iapreceipthistory',
            name='iap_digest',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='\u82f9\u679c\u652f\u4ed8\u9a8c\u8bc1\u4e32\u7684md5\u503c'),
        ),
        migrations.AlterField(
            model_name='iapreceipthistory',
            name='bundle_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='iOS bundle_id'),
        ),
        migrations.AlterField(
            model_name='iapreceipthistory',
            name='trade_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='\u652f\u4ed8\u4e2d\u5fc3\u8ba2\u5355id'),
        ),
    ]
