# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_thirdpartyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paytype', models.CharField(choices=[('wechatpay', 'wechatpay'), ('alipay', 'alipay'), ('tencentpay', 'tencentpay'), ('googlepay', 'googlepay'), ('unionpay', 'unionpay'), ('iap', 'iap')], max_length=64)),
                ('info', models.TextField(blank=True, null=True, verbose_name='in JSON format')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.App')),
            ],
        ),
        migrations.RemoveField(
            model_name='fbuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='googleuser',
            name='user',
        ),
        migrations.AlterField(
            model_name='thirdpartyappinfo',
            name='thirdparty',
            field=models.CharField(choices=[('facebook', 'facebook'), ('google', 'google'), ('qq', 'qq'), ('wechat', 'wechat'), ('weibo', 'weibo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='usergameorder',
            name='pay_channel',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='\u652f\u4ed8\u901a\u9053\uff08100:\u652f\u4ed8\u5b9d\uff1b99:\u82f9\u679c\u652f\u4ed8\uff1b98:\u94f6\u8054\u652f\u4ed8\uff1b96:\u8c37\u6b4c\u652f\u4ed8\uff09'),
        ),
        migrations.DeleteModel(
            name='FBUser',
        ),
        migrations.DeleteModel(
            name='GoogleUser',
        ),
        migrations.AlterUniqueTogether(
            name='apppayinfo',
            unique_together=set([('app', 'paytype')]),
        ),
    ]
